Fix Docker container page look incompletely
dotnetthailand/dotnetthailand.github.io pull request #155
Opened 2021-10-12 20:38 UTC by Eji4h

I fix my issue #62.

2021-10-13 06:10 UTC, dmakeroam requested changes

2021-10-13 06:10 UTC, dmakeroam commented on content/faq/docker/docker-container.md
> +# To list all container
list all containers? Plural?

2021-10-13 06:10 UTC, dmakeroam commented on content/faq/docker/docker-container.md
>  # To copy files/folders between container and local filesytem
containers and local filesystem?

2021-10-13 06:10 UTC, dmakeroam commented on content/faq/docker/docker-container.md
>  # To run command in container
To run a command?

2021-10-13 17:57 UTC, Eji4h commented on content/faq/docker/docker-container.md
> +# To list all container
I don't change this. Just format.

2021-10-13 18:10 UTC, Eji4h commented on content/faq/docker/docker-container.md
> +# To list all container
This is legacy wording. Sorry for only focus #62 issue.

2021-10-13 18:16 UTC, Eji4h commented
I think maintainers can update the wording to be proper. I am not confident in my English and grammar skills. My PR is only focused on the #62 issue.

Thanks

2021-10-16 01:39 UTC, aaronamm commented
@dmakeroam  I have fixed singular/plural nouns already. Thanks for your feedback.

2021-10-16 01:40 UTC, aaronamm commented
@Eji4h Since this is a small PR (only one changed file), could you please squash all commit messages to one message.
Thanks.

![image](https://user-images.githubusercontent.com/2938310/137568682-b283351d-f6d4-426d-a1c4-8703d42882f6.png)

2021-10-16 16:11 UTC, closed without merging