three way to insert css (stylesheet)
dotnetthailand/dotnetthailand.github.io pull request #168
Opened 2021-10-24 16:53 UTC by iamgique

2021-10-25 16:26 UTC, mildronize requested changes
Thank you for your PR.

I have some suggestion that you should fix your content

The topic should be changed, I think "Importing CSS to HTML"

The rest is ok, it would be better if you give some brief explanation on each context. Thank you very much.

Happy Hacktoberfest

2021-10-25 16:26 UTC, mildronize commented on content/frontend-web/insert-css.md
> +When browser read style sheet it will manage format the HTML doc to the information is style sheet.
Incorrect English Grammar, most context is confuse, you can use Thai in .NET Thailand

2021-10-25 16:26 UTC, mildronize commented on content/frontend-web/insert-css.md
> +```
```
->> use  ```css  , not  ```cs
```

2021-10-25 16:26 UTC, mildronize commented on content/frontend-web/insert-css.md
> +```
```
->> use  ```css  , not  ```cs
```

2021-10-25 16:26 UTC, mildronize commented on content/frontend-web/insert-css.md
> +```
```
->> use  ```css  , not  ```cs
```

2021-10-25 16:26 UTC, mildronize commented on content/frontend-web/insert-css.md
> +```
```
->> use  ```css  , not  ```cs
```

2021-10-26 02:41 UTC, iamgique commented
@mildronize Thank you for your suggestion, I've done.

2021-10-26 02:43 UTC, mildronize approved these changes

2021-10-26 02:44 UTC, mildronize commented
Good Job. Thank you for your contribution. Merged. @iamgique

2021-10-26 02:44 UTC, merged