Introduction to RepoDb Part1
dotnetthailand/dotnetthailand.github.io pull request #175
Opened 2021-10-27 17:14 UTC by kchinburarat

Document about Repodb , a hybrid-ORM library for .NET

2021-10-28 05:10 UTC, teerasej commented
I fixed a little typo on this PR. But we need you for technical content @aaronamm 👍

2021-10-28 05:26 UTC, aaronamm commented
@teerasej Thank you for your supporting. However, you can add a review comment to where there are typos and let PR owner fixt it. I think it is the prefer way.

2021-10-28 05:33 UTC, aaronamm commented
@kchinburarat  Could you please change your branch to your origin?
![image](https://user-images.githubusercontent.com/2938310/139193017-95bf2e87-0a52-4bac-ab02-e96ec0ae7a1b.png)

For making a PR, we should make a new branch from our origin.
Thanks.

2021-10-28 05:54 UTC, aaronamm requested changes
@kchinburarat very nice PR, keep going.
I have only minor feedback. After you have fixed them, I will merge your PR.
BTW, is it possible for you to put some content that why we need to consider Repodb what is its benefit over Dapper.
I haven't use it but the raw query API looks similar to Dapper.

Thanks.

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +ด้วยเหตุนี้เอง เราในฐานะนักพัฒนาจึงมีหน้าที่เลือกสิ่งที่ดีที่สุดสำหรับความต้องการของเราเพราะเราต้องคำนึงถึง เวลาในการพัฒนา,ความเรียบง่าย,ประสิทธิภาพ ฯลฯ
Vey minor, not sure we need comma for Thai word. If you want to keep it, please put one space after each comma.

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +.NET
Should we move .NET to the same line as the above line?

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +เราจะเรียก RepoDb ว่า hybrid-ORM ก็พราะว่ามันมีคสามสามารถที่ micro-ORM และ full-ORM มีในการที่มันทำให้เกิดความยืดหยุ่นแก่นักพัฒนาในการทำให้งานเกี่ยวกับ Database
Typo `คสาม` => `ความ`

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +หรือจะให้แบบการเรียก `method-based`
Should we change it to `หรือจะเรียกใช้แบบ`?

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +// Query
Very minor, I am not sure we should change `Query` to `Select`.

2021-10-28 05:54 UTC, aaronamm commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +การดำเนินการแบบแบตช์ในไลบรารีนี้เป็นคำสั่งแบบแพ็กทั้งหมด โดย DbCommand เดียวใช้เพื่อดำเนินการคำสั่ง SQL หลายรายการในครั้งเดียว กระบวนการนี้เป็น ACID โดยค่า default chunk คือ 10 records ลองดูตัวอย่างด
Could you please add parentheses of what ACID stand for and change it to a useful link that explains what ACID is?

2021-10-28 05:59 UTC, teerasej commented
> @teerasej Thank you for your supporting. However, you can add a review comment to where there are typos and let PR owner fixt it. I think it is the prefer way.

ok, sorry about that 👍

2021-10-28 09:44 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +// Query
We do select but the method name is Query so I prefer to use the word `Query` :)

2021-10-28 09:50 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +การดำเนินการแบบแบตช์ในไลบรารีนี้เป็นคำสั่งแบบแพ็กทั้งหมด โดย DbCommand เดียวใช้เพื่อดำเนินการคำสั่ง SQL หลายรายการในครั้งเดียว กระบวนการนี้เป็น ACID โดยค่า default chunk คือ 10 records ลองดูตัวอย่างด
fixed

2021-10-28 09:50 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +หรือจะให้แบบการเรียก `method-based`
fixed

2021-10-28 09:50 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +เราจะเรียก RepoDb ว่า hybrid-ORM ก็พราะว่ามันมีคสามสามารถที่ micro-ORM และ full-ORM มีในการที่มันทำให้เกิดความยืดหยุ่นแก่นักพัฒนาในการทำให้งานเกี่ยวกับ Database
fixed

2021-10-28 09:50 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +.NET
fixed

2021-10-28 09:51 UTC, kchinburarat commented on content/faq/libraries-frameworks/orm/RepoDb/repodb-hybrid-orm-part1.md
> +ด้วยเหตุนี้เอง เราในฐานะนักพัฒนาจึงมีหน้าที่เลือกสิ่งที่ดีที่สุดสำหรับความต้องการของเราเพราะเราต้องคำนึงถึง เวลาในการพัฒนา,ความเรียบง่าย,ประสิทธิภาพ ฯลฯ
fixed

2021-10-31 09:11 UTC, aaronamm commented
@kchinburarat Good job. Thanks.

2021-10-31 09:12 UTC, aaronamm approved these changes

2021-10-31 09:12 UTC, merged