Docker file
dotnetthailand/dotnetthailand.github.io pull request #178
Opened 2021-10-28 06:41 UTC by utarn

2021-11-01 16:56 UTC, dmakeroam commented on content/faq/dotnet/dotnet-cli.md
> +จากตัวอย่างคำสั่ง จะสร้างระบบ Authentication ด้วย ASP.NET Identity ที่ใช้ local database ซึ่งหากสร้างโปรเจคนี้ใน Visual Studio โปรแกรม Visual Studio จะเลือกใช้ฐานข้อมูล SQL Server LocalDB ให้อัตโนมัต
fix: typo: โปรแกรม

2021-11-01 17:12 UTC, dmakeroam requested changes

2021-11-01 17:12 UTC, dmakeroam commented on content/faq/dotnet/dotnet-cli.md
> +จากตัวอย่างคำสั่ง จะสร้างระบบ Authentication ด้วย ASP.NET Identity ที่ใช้ local database ซึ่งหากสร้างโปรเจคนี้ใน Visual Studio โปรแกรม Visual Studio จะเลือกใช้ฐานข้อมูล SQL Server LocalDB ให้อัตโนมัต
fix: typo: โปรแกรม

2021-11-24 14:57 UTC, utarn commented
sorry for the late fix.

2021-11-25 16:37 UTC, aaronamm commented
@utarn Thanks for your contribute. @dmakeroam will continue review your PR and he will merge it if all PR feedbacks have been fixed.
Thanks.

2021-11-26 12:06 UTC, merged