Add Basic of unit testing (in Thai)
dotnetthailand/dotnetthailand.github.io pull request #182
Opened 2021-10-29 02:50 UTC by duangrudee

Add Basic of unit testing (in Thai)

2021-10-30 14:55 UTC, aaronamm commented
@duangrudee  Thank you so much for your contribution.

2021-11-06 15:23 UTC, kchinburarat requested changes
please fix typo
the rest is good kub

2021-11-06 15:25 UTC, kchinburarat commented on content/testing/unit-testing-basic.md
> +- Do you want to write better code? การเขียน code ให้ testable ได้นั้น จะทำให้ code ของคุณถูก refactor / organized ไปโดยอัตโนมัติ และ code ที่ดีนั้นแท้จริงแล้ว ัมันก็คือ code ที่รันได้อย่างถูกต้องและ
ที่ดีนั้นแท้จริงแล้ว ัมันก็คือ <=  ตรงนี้ครับ

2021-11-24 10:34 UTC, kchinburarat approved these changes

2021-11-24 10:34 UTC, merged