add: vim replacement inside visual selection
dotnetthailand/dotnetthailand.github.io pull request #199
Opened 2021-10-31 15:32 UTC by cckcoder

add one more tip for replacement in vim

2021-11-02 14:11 UTC, mildronize requested changes
Good PR. Please change following my suggestion. 

Thank you for your contribution.

2021-11-02 14:11 UTC, mildronize commented on content/programming-cookbook/vim-and-neovim/replacement-inside-visual-selection.md
> +- then `:s/let/var/g <CR>`
I think you should explain how that command works.

2021-11-02 14:11 UTC, mildronize commented on content/programming-cookbook/vim-and-neovim/replacement-inside-visual-selection.md
> +title: replacement inside visual selection
Please use Big Letter => "Replacement inside visual selection"

2021-11-03 02:56 UTC, aaronamm commented
@mildronize Thank you so much for reviewing this PR.

2022-10-12 12:40 UTC, aaronamm approved these changes
Thank you for useful content.

2022-10-12 12:41 UTC, merged