add: how to exit vim
dotnetthailand/dotnetthailand.github.io pull request #212
Opened 2022-10-22 07:56 UTC by cckcoder

2022-10-22 08:25 UTC, ninefyi approved these changes
Thank you for your contribution.
It looks good to me.

2022-10-23 09:22 UTC, aaronamm commented on content/programming-cookbook/vim-and-neovim/how-exit-vim.md
> +![demo](images/how-to-exit-vim.jpg)
Nice introduction.

2022-10-23 09:23 UTC, aaronamm commented on content/programming-cookbook/vim-and-neovim/how-exit-vim.md
> +  * wait... if you exit vim with `:q` it not be saved what you edit.
Very small change, please use capital W.

2022-10-23 09:24 UTC, aaronamm requested changes
Please update your PR from my feedback. Then I will merge it.

Thank you.

2022-12-06 14:12 UTC, aaronamm approved these changes

2022-12-06 14:12 UTC, merged